### ISSUE TITLE
(Feature) Handle multiple addresses from PoPA

### ISSUE THREAD

**Issue by unjapones** [oraclesorg/oracles-dapps-validators#80] opened 2018-08-28 23:28 UTC
Issues #75 and #78 render only one address from PoPA on the UI, but the `ProoOfPhysicalAddress` contract can store multiple confirmed and unconfirmed physical addressed of a given validator. This ticket is meant to cover these scenarios and how the UI should render the data.

Some suggestions:

* Render the first (confirmed or unconfirmed) physical address and show a tooltip/accordeon/etc to reveal the extra addresses.
* Just a tooltip that states that the validator has multiple addresses, either confirmed or unconfirmed.
* A link to the PoPA DApp, although we should add the corresponding feature to the UI of the latter DApp.

**Comment by varasev** [comment] 2018-08-29 10:16
@igorbarinov is it enough to show in Validators DApp only the first confirmed address for each validator? What do you think?

**Comment by igorbarinov** [comment] 2018-08-29 11:28
Hi guys. I'd like to see all confirmed addresses for a validator. It will bring more transparency into the process.

**Comment by pablofullana** [comment] 2018-08-29 12:30
@igorbarinov @varasev what about those addresses that have been registered but not confirmed yet. For example, those for which a validator is waiting for the post card to arrive. Shall we display those as well?

**Comment by varasev** [comment] 2018-08-29 13:01
@pablofullana I think we should display them too, but with `Unconfirmed` label.

**Comment by varasev** [comment] 2018-08-30 10:24
This issue seems to be duplicated in https://github.com/poanetwork/poa-dapps-validators/issues/78. Maybe close this one and continue the discussion there?

**Closed as completed** 2018-09-20 13:15 UTC
