### ISSUE TITLE
Retrieve validators' physical addresses from PoPA dapp

### ISSUE THREAD

**Issue by pablofullana** [oraclesorg/oracles-dapps-validators#74] opened 2018-08-16 16:07 UTC
- [x] Retrieve validators' physical addresses from PoPA dapp rather than from validators dapp registry.
- [x] Display the physical address in the same way it's being displayed nowadays. Evaluate adding a green circle (or any other visual aid) to state the fact of confirmation.

Open questions may have to be addressed in new issues:
1. Display only confirmed physical addresses or can we display unconfirmed ones (with some visual aid to reflect the fact of the pending confirmation)
1. Can a validator have multiple physical addresses? How to deal with this from a frontend perspective?
1. Evaluate removing physical addresses from validators dapp registry

**Comment by unjapones** [comment] 2018-08-27 17:31
@phahulin @pablofullana the PR https://github.com/poanetwork/poa-dapps-validators/pull/75 only covers a simple scenario and implements a basic UI representation: 

> render the validator's _confirmed_ address with a highlighted color + a tooltip on hover only if the validator has a confirmed address.

As @pablofullana said, there are different scenarios not covered by the PR. May we discuss here what we expect to do next?

Personally I think the next step is decide to "**1) gradually deprecate**" or "**2) just drop** the usage of the address data from Validator's DApp registry.

The two courses of actions _always imply rendering what we get from PoPA_, emphasize that the data was retrieved from that contract and highlight confirmed addresses. The only difference between 1) and 2) is: if PoPA doesn't have a validator's address, then 1) will render what we have on the Validator's DApp registry and 2) will render nothing (_and will probably induce validators to, at least, register their address on PoPA Dapp?_).

I think the scenarios for multiple addresses (registered or confirmed) should be treated in a different issue, but that's my opinion.

p/s: should we involve the designer (`@pashagonchar`?) in this discussion?

**Comment by pablofullana** [comment] 2018-08-27 17:37
Good questions @unjapones. Let's open a new issue for these different scenarios and which "adoption" approach will follow.

Let's add @varasev and @igorbarinov to the discussion as well, for a product-business perspective. And also @pashagonchar for a design-oriented guidance.

**Comment by unjapones** [comment] 2018-09-21 17:51
@varasev I believe this issue can be safely closed, since the PR https://github.com/poanetwork/poa-dapps-validators/pull/75 has been merged, right?

**Comment by varasev** [comment] 2018-09-22 07:59
@unjapones Yes, I closed this.

**Closed as completed by varasev** 2018-09-22 07:59 UTC
